:bug: fix seed for example data generation
fixes issue where 'using-xmaps.Rmd' was not consistently rendering
  due to generated data not covering all possible category values
  causing a "column not found" error after pivoting the data

ERROR:
   --- re-building ‘using-xmaps.Rmd’ using rmarkdown
   Quitting from lines 269-286 (using-xmaps.Rmd)
   Error: processing vignette 'using-xmaps.Rmd' failed with diagnostics:
   Problem while evaluating `dplyr::all_of(baby_pets)`.
   Caused by error in `dplyr::all_of()`:
   ! Can't subset elements that don't exist.
   ✖ Element `puppy` doesn't exist.